### ISSUE TITLE
Delta change: update the historical run period

### ISSUE THREAD

**Issue by hboisgon** [Deltares/blueearth_cst#112]
So far for the delta change run we use the same period as the historical hydrology workflow.
Because this first workflow checks with observations, it may be better to use a different period for the historical run in the historical hydrology workflow and the future one with delta change.

Config extract:
``` yaml
# Info on the historical climate data is used in the historic model run + reference data for the weather generator
# Time horizon of the historical period
starttime: "1980-01-01T00:00:00"
endtime: "2020-12-31T00:00:00"

# time horizons of the climate projections
start_month_hyd_year: JAN
historical: 1980, 2010
future_horizons: 
  near: 2035, 2065
  far: 2070, 2100
```

Idea would be to use historical period from the climate projections instead of the starttime/endtime from the model creation workflow.
