### ISSUE TITLE
Reorganize the config file structure

### ISSUE THREAD

**Issue by hboisgon** [Deltares/blueearth_cst#140]
With more workflows, the structure of the config file with "one level" becomes too unstructured and prone to errors.
It would be nice to re-organise the config in sections: one general section for common options between workflows and one section per snakemake workflow.

eg for climate projections

``` yaml
 
global:
  project_dir: my_project  
  region: "{'basin': [x, y]}"
  start_month_hyd_year: JAN
 
climate_projections:
  source: cmip6
  models: ['NOAA-GFDL_GFDL-ESM4', 'INM_INM-CM5-0', 'CSIRO-ARCCSS_ACCESS-CM2']
  scenarios: [ssp245, ssp585]
  members: [r1i1p1f1]
  time_horizons:
    historical: 2000, 2010
    future: 
      near: 2050, 2060
      far: 2090, 2100
  variables: [precip, temp, temp_dew, kin, tcc, wind]
  compute_variables:
    pet_method: makkink
    compute_wind: False
    compute_tdew: True
  change_factors:
    save_grids: TRUE
    drymonth_threshold: 3.0
    drymonth_maxchange: 50
 
```

instead of 

```yaml

# global settings
project_dir: my_project  
region: "{'basin': [x, y]}"
start_month_hyd_year: JAN

# climate projections
clim_project: cmip6
models: ['NOAA-GFDL_GFDL-ESM4', 'INM_INM-CM5-0', 'CSIRO-ARCCSS_ACCESS-CM2']
scenarios: [ssp245, ssp585]
members: [r1i1p1f1]
historical: 2000, 2010
future_horizons: 
  near: 2050, 2060
  far: 2090, 2100
variables: [precip, temp, temp_dew, kin, tcc, wind]
pet_method: makkink
compute_wind: False
compute_tdew: True
save_grids: TRUE
change_drymonth_threshold: 3.0
change_drymonth_maxchange: 50

```
