### ISSUE TITLE
add precip_fn source in config file to be more flexible with using prec and temp from different sources and compare the runs 

### ISSUE THREAD

**Issue by laurenebouaziz** [Deltares/blueearth_cst#144]
now in the config file we have: 

```
forcing_options:
  era5: # clim/precip source name
    temp_pet_fn: era5 # data source for temperature and pet if computed
    pet_fn: # direct data source for pet else will be computed using the temp data source
    dem_forcing_fn: era5_orography # data source for orography for downscaling temperature
    pet_method: debruin # method to compute pet
    press_correction: True
  chirps_global:
    temp_pet_fn: era5
    dem_forcing_fn: era5_orography
    pet_method: debruin
    press_correction: True
  imdaa:
    temp_pet_fn: imdaa
    dem_forcing_fn: 
    pet_method: debruin
    press_correction: False
```

if later we want to compare era5_precip + imdaa_temp and era5_precip + era5_temp, we might want to change to:
```
forcing_options:
  era5_P_imdaa_T: # custom clim name 
    prec_fn: era5 # precip source name
    temp_pet_fn: imdaa # data source for temperature and pet if computed
    pet_fn: # direct data source for pet else will be computed using the temp data source
    dem_forcing_fn: era5_orography # data source for orography for downscaling temperature
    pet_method: debruin # method to compute pet
    press_correction: True
```

@hboisgon, perhaps you already mentioned this? as you mentioned something about restructuring the config file with respect to this section aswell:

```
clim_historical: 
  - era5
  - chirps_global
  - imdaa

clim_historical_colors:
  - blue
  - lightblue
  - green
```
